### PR TITLE
Add compatibility for python3

### PR DESCRIPTION
**Pull request by nsorros**
This PR aims to make the code compatible with Python3 when running with an input file.

There were two problems that needed fixing
* cPickle which has been replaced with pickle
* print statement in loaders

### CODE REVIEW

**Comment by kylase** [comment]
Thanks for the submitting the PR. However, I am holding onto a branch that is Python 3 compatible, which has the same changes you made. Therefore, I won't be merging your changes.

**Comment by hblanks** [comment]
@kylase  - thanks for the review! But we'd love to get Python 3 support in, as otherwise we're obliged to maintain our own fork of the project.

Could @nsorros  or I either help you get PR #11 merged, or help you split it into one change for Python 3 compatibility, and one for the training fix?

**Comment by kylase** [comment]
Thanks for the offer! 
I am working on #11 this week and should be able to merge it by end of this week. 🤞

**Comment by knmnyn** [comment]
Thank you all for your continued support of Neural ParsCit! @kylase is our key developer at this point and is looking at scalability issues, just FYI.

**Comment by kylase** [comment]
@nsorros and @hblanks I have released a patch that incorporated minor Python 3 compatibility. You can try it out and let me know if there are issues.

**Pull request closed without merging**
