### PR TITLE
Feature/pytorch

### PR DESCRIPTION
**Pull request by kylase**

### CODE REVIEW

**Comment by knmnyn** [comment]
Working now with PyTorch 1.0?

**Comment by knmnyn** [comment]
Didn't see a description of the PR, so asking. 😃

**Comment by kylase** [comment]
I accidentally created the PR as I was pushing the latest model up. Sorry.

**Comment by knmnyn** [comment]
No worries.
Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Pull request closed without merging**
